# Generated by Django 3.1.4 on 2020-12-15 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=32)),
                ('link', models.CharField(max_length=128)),
                ('descr', models.TextField(max_length=256)),
            ],
        ),
    ]
