# Generated by Django 3.1.4 on 2020-12-16 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_item_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='image',
        ),
        migrations.RemoveField(
            model_name='item',
            name='page',
        ),
    ]
