# Generated by Django 3.1.4 on 2020-12-16 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20201216_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='descr',
            field=models.TextField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='item',
            name='link',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='item',
            name='title',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='page',
            name='title',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
