# Generated by Django 3.1.4 on 2020-12-16 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20201216_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='page',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.page'),
            preserve_default=False,
        ),
    ]
