# Generated by Django 3.1.4 on 2020-12-16 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_item_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='page',
        ),
    ]
